name: gds

on:
  push:
  workflow_dispatch:

jobs:
  gds:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Read top module name
        id: top_module
        run: |
          echo "TOP_MODULE=$(yq '.project.top_module' info.yaml)" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: pip install klayout

      - name: Generate dummy GDS
        run: python scripts/gen_gds.py

      - name: Create and publish the GDS artifact
        uses: TinyTapeout/tt-gds-action/custom_gds@ttsky26a
        with:
          top_module: ${{ steps.top_module.outputs.TOP_MODULE }}
          gds_path: gds/${{ steps.top_module.outputs.TOP_MODULE }}.gds
          lef_path: src/macro/yen_top.lef
          verilog_path: src/tt_um_multi_stage_processor.v
          pdk: sky130A

  precheck:
    needs: gds
    runs-on: ubuntu-24.04

    steps:
      - name: Run Tiny Tapeout Precheck
        uses: TinyTapeout/tt-gds-action/precheck@ttsky26a

  viewer:
    needs: gds
    runs-on: ubuntu-24.04
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Run GDS Viewer
        uses: TinyTapeout/tt-gds-action/viewer@ttsky26a
